name: WeaponHolder
version: 1.1
main: me.PvPNiK.wh.WeaponHolder

commands:
  weaponholder:
    aliases: [wh]

permissions:
  weaponholder.reload:
    description: reloads worlds.yml and itemPosition.yml