name: WeaponHolder
version: 1.2
main: me.pvpnik.weaponHolder.WeaponHolder

commands:
  weaponholder:
    aliases: [wh]

permissions:
  weaponholder.reload:
    description: reloads worlds.yml and itemPosition.yml