name: WeaponHolder
version: 1.5
main: me.pvpnik.weaponHolder.WeaponHolder

commands:
  weaponholder:
    aliases: [wh]

permissions:
  weaponholder.reload:
    description: reloads worlds.yml and itemPosition.yml
  weaponholder.bypass:
    description: allows the player get other player item